### ISSUE TITLE
radial rotation

### ISSUE THREAD

**Issue by dicook** [nspyrison/spinifex#13]
- [x] should run from current state, down to 0, then up to 1, then back to current state
- [x] manip var could be added as an attribute?

**Comment by nspyrison** [comment]
![img_20181005_102457](https://user-images.githubusercontent.com/6053779/46509951-39c3ad00-c889-11e8-811a-97380016d68e.jpg)

**Comment by dicook** [comment]
Nice picture!

**Comment by nspyrison** [comment]
The manual_tour walks will never allow norm(manip_var) to be 1 as the norm of the other variables have distance and the basis is orthonormal. could scale the unit circle to the norm(manip_var) or max(norm(any_var)) though.

**Comment by nspyrison** [comment]
currently not working when the manip_var has x>0.

**Comment by nspyrison** [comment]
sign fixed when manip_var has x>0. does go down to 0, but the segement still has sizable distance even when both x and y are near zero (ie e-16)
