### ISSUE TITLE
fix plotly issue: slide 1 of label positions

### ISSUE THREAD

**Issue by dicook** [nspyrison/spinifex#23]

**Comment by nspyrison** [comment]
render_slideshow() plotly obj, does slide one have the correct positions for the text labels?

**Comment by nspyrison** [comment]
axes and text use the same positions. issue seem to be an artifact of plotly rather than the data struc.

**Comment by nspyrison** [comment]
labels don't want to render with the scatterplot points. for now just using scatterplot.

**Comment by nspyrison** [comment]
reproduced error and issue opened on Plotly repo. workaround: is to add 9^-9 to the reference axes, this seems to resolve the issue. Tooltops need to be removed seprately.
