### ISSUE TITLE
fix plotly render of scatter plot data.

### ISSUE THREAD

**Issue by dicook** [nspyrison/spinifex#24]

**Comment by nspyrison** [comment]
render_slideshow() plotly obj scatterplot correctly showing.

**Comment by dicook** [comment]
this is fixed. data is also centred. 

BUT the problem is related to the geom_text somehow. Drawing the text labels messes with the point drawing. Labels are turned off to fix it currently.

**Comment by nspyrison** [comment]
there seems to be an issue when using multiple layers of different dim. issue was opened on plotly repo. Current workaround: add 9^-9 to the reference basis, this seems to allow for correct display in all frames.
