### ISSUE TITLE
Warning message looks like there is an issue

### ISSUE THREAD

**Issue by dicook** [nspyrison/spinifex#31]
> flea_std <- tourr::rescale(tourr::flea[,1:6])
> rb <- tourr::basis_random(n = ncol(flea_std))
> class <- tourr::flea$species
> 
> play_manual_tour(basis = rb, data = flea_std, manip_var = 4)
Scale for 'shape' is already present. Adding another scale for 'shape',
which will replace the existing scale.

**Comment by nspyrison** [comment]
even when no shape passed, ggplot2 still throws error about aes(), review after changes from issue #32.

**Comment by nspyrison** [comment]
fixed in 0.2.5 release, 6/18/2020.
