### ISSUE TITLE
point size not being accepted 

### ISSUE THREAD

**Issue by dicook** [nspyrison/spinifex#32]
setting size=2 (or anything) is ignored by play_manual_tour() and render_plotly()

**Comment by nspyrison** [comment]
ggplot2::aes() not responding to all aesthetic arguments.
shape = pch, color = col, fill = col, size = cex, alpha = alpha

**TODO:** 
- either: cbind() aes args to df or otherwise perform condition handing on aes() args.

**Comment by nspyrison** [comment]
Fixed in v0.2.5 release, 6/18/2020.
